name: Package & Release Addons

on:
  push:
    tags:
      - 'v*'
      - '*/*'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        addon:
          - name: 'Grouperio'
            path: 'Grouperio'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Packager for ${{ matrix.addon.name }}
        uses: BigWigsMods/packager@v2
        with:
          args: -p ${{ matrix.addon.path }}/${{ matrix.addon.name }}.toc
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
