name: Package & Release Addons

on:
  push:
    tags:
      - 'v*'
      - '*/*'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        addon:
          - name: 'Grouperio'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Packager for ${{ matrix.addon.name }}
        uses: BigWigsMods/packager@v2
        # Optional: add -p <CurseForge_Project_ID> here if it's not declared inside your .toc file
        # with:
        #   args: -p 123456
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
